name: Release to crates.io

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Run cargo check
      run: cargo check
    - name: Login crates.io
      run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - run: cargo publish
