name: Publish to Github

on:
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Create artifacts directory
      run: mkdir artifacts
    - name: Get the release version from the tag
      run: |
        echo "SK_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.SK_VERSION }}
        body: ${{ env.SK_VERSION }}
        draft: false
        prerelease: false
    - name: Save release upload URL to artifact
      run: echo "${{ steps.release.outputs.upload_url }}" > artifacts/release-upload-url
    - name: Save version number to artifact
      run: echo "${{ env.SK_VERSION }}" > artifacts/release-version
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts

  publish:
    name: Publish
    needs: ['create-release']
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build: [linux, linux-arm, linux-arm-v7, linux-aarch64, linux-mips, macos, macos-aarch64]
        rust: [stable]
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          cross: false
        - build: linux-arm
          os: ubuntu-latest
          target: arm-unknown-linux-gnueabihf
          cross: true
        - build: linux-arm-v7
          os: ubuntu-latest
          target: armv7-unknown-linux-gnueabihf
          cross: true
        - build: linux-aarch64
          os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
          cross: true
        - build: linux-mips
          os: ubuntu-latest
          target: mips-unknown-linux-musl
          cross: true
        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin
          cross: false
        - build: macos-aarch64
          os: macos-latest
          target: aarch64-apple-darwin
          cross: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: ${{ matrix.target }}

    - name: Get release download URL
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: artifacts
    - name: Set release upload URL and release version
      shell: bash
      run: |
        release_upload_url="$(cat artifacts/release-upload-url)"
        echo "RELEASE_UPLOAD_URL=$release_upload_url" >> $GITHUB_ENV
        echo "release upload url: $RELEASE_UPLOAD_URL"
        release_version="$(cat artifacts/release-version)"
        echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
        echo "release version: $RELEASE_VERSION"

    - name: Run cargo build
      run: cargo build --release --target ${{ matrix.target }}
      if: ${{ !matrix.cross }}

    - name: Run cross build
      run: |
        cargo install cross
        cross build --release --target ${{ matrix.target }}
      if: ${{ matrix.cross }}

    - name: Package Artifacts
      run: |
        src=$(pwd)
        stage=

        case $RUNNER_OS in
            Linux)
                stage=$(mktemp -d)
                ;;
            macOS)
                stage=$(mktemp -d -t tmp)
                ;;
        esac

        echo "src is: $src"
        echo "stage is: $stage"

        cp target/${{ matrix.target }}/release/sk $stage/
        cd $stage

        ASSET_NAME="skim-${{ env.RELEASE_VERSION }}-${{ matrix.target }}.tar.gz"
        ASSET_PATH="$src/$ASSET_NAME"
        echo "ASSET_NAME=$ASSET_NAME" >> $GITHUB_ENV
        echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV

        tar czf $ASSET_PATH *

        cd $src
    - name: Upload release archive
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.RELEASE_UPLOAD_URL }}
        asset_path: ${{ env.ASSET_PATH }}
        asset_name: ${{ env.ASSET_NAME }}
        asset_content_type: application/octet-stream
